
export const BACK_BUTTON = 'BACK_BUTTON'
export const UPDATE_CORE_DATA = 'UPDATE_CORE_DATA'

export const TOGGLE_NAV_MENU = 'TOGGLE_NAV_MENU'
export const OPEN_NAV_MENU = 'OPEN_NAV_MENU'
export const CLOSE_NAV_MENU = 'CLOSE_NAV_MENU'
export const FULL_NAV_MENU = 'FULL_NAV_MENU'

export const REQUEST_RANDOM_USER = 'REQUEST_RANDOM_USER'
export const USER_PROFILE_RECEIVED = 'USER_PROFILE_RECEIVED'
export const USER_PROFILE_REPOS_RECEIVED = 'USER_PROFILE_REPOS_RECEIVED'

export const CLEAR_USER_REPOS_PAGE = 'CLEAR_USER_REPOS_PAGE'
export const USER_REPOS_REQUEST = 'USER_REPOS_REQUEST'
export const USER_REPOS_RECEIVED = 'USER_REPOS_RECEIVED'
export const USER_REPOS_NEXT_PAGE_RECEIVED = 'USER_REPOS_NEXT_PAGE_RECEIVED'
export const USER_REPOS_COMPLETE = 'USER_REPOS_COMPLETE'

export const REPO_DETAIL_RECEIVED = 'REPO_DETAIL_RECEIVED'
export const REPO_README_RECEIVED = 'REPO_README_RECEIVED'
export const REPO_CONTENTS_RECEIVED = 'REPO_CONTENTS_RECEIVED'
export const REPO_LANGUAGES_RECEIVED = 'REPO_LANGUAGES_RECEIVED'
export const DETAIL_TRANSITION_DATA = 'DETAIL_TRANSITION_DATA'
export const REPO_DETAIL_REQUEST_PAGE_FAILED = 'REPO_DETAIL_REQUEST_PAGE_FAILED'
export const REPO_DETAIL_RECEIVED_ALL = 'REPO_DETAIL_RECEIVED_ALL'
export const CLEAR_REPO_DETAIL_PAGE = 'CLEAR_REPO_DETAIL_PAGE'

export const TRIGGER_LOAD_ANIMATION = 'TRIGGER_LOAD_ANIMATION'
export const TRIGGER_LOAD_ANIMATION_DONE = 'TRIGGER_LOAD_ANIMATION_DONE'
export const TRIGGER_LOAD_ANIMATION_HIDE = 'TRIGGER_LOAD_ANIMATION_HIDE'
export const TRIGGER_LOAD_ANIMATION_FAILED = 'TRIGGER_LOAD_ANIMATION_FAILED'
export const TRIGGER_LOAD_ANIMATION_RESET = 'TRIGGER_LOAD_ANIMATION_RESET'

export const CLEAR_USER_PAGE = 'CLEAR_USER_PAGE'
export const USERS_RECEIVED = 'USERS_RECEIVED'
export const USERS_REQUEST = 'USERS_REQUEST'
